### ISSUE TITLE
Multiple patterns

### ISSUE THREAD

**Issue by pooledge** [srmeyers/git-prefix#10]
Thanks for this great extension!

I'm in need of defining multiple patterns when switching between multiple projects, i.e. multiple projects might have different issue naming format (BACK-\\d vs. FRNT-\\d).

Right now, naturally the _Pattern not found in branch_ message is displayed. Any plans of implementing this in the future?

**Comment by Yilong94** [comment]
I encountered a similar issue. What I did was that for different project, you can define different patterns for different projects under the `Workspace` setting.

**Comment by pooledge** [comment]
> I encountered a similar issue. What I did was that for different project, you can define different patterns for different projects under the `Workspace` setting.

That was it! Case closed!
