### ISSUE TITLE
Icon no longer visible after vscode update

### ISSUE THREAD

**Issue by welcometochristown** [srmeyers/git-prefix#12]
After the last vscode update the icon is now just a dot that is hard to click.

![image](https://user-images.githubusercontent.com/17158437/118160456-52ef4b80-b3ec-11eb-8ede-8dbfae3cf507.png)

Version: 1.56.1 (user setup)
Commit: e713fe9b05fc24facbec8f34fb1017133858842b
Date: 2021-05-06T10:08:05.141Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by srmeyers** [comment]
After I updated, the button icon is still displaying correctly.

Version: 1.56.2 (user setup)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:13:13.157Z

**Comment by welcometochristown** [comment]
Just updated my VSCode again and now its fixed. Very strange.
