### ISSUE TITLE
Prefix button stopped working recently

### ISSUE THREAD

**Issue by eljenso** [srmeyers/git-prefix#22]
The button in the source control panel recently stopped working. 
When clicking on the button (see screenshot), nothing happens. Not even an error is shown if the branch name does not fit the pattern setting.

However, when using the command from the command pallet, the prefix is correctly added.

I can't really tell if this happened with the recent VS Code update or even before that.

![image](https://user-images.githubusercontent.com/2805194/206696685-7548d2db-ad5f-4c64-b11b-806ec2593f33.png)

---

Custom extension settings:
```
"gitPrefix.pattern": ".*\\/(\\D+-\\d+).*",
"gitPrefix.replacement": "$1 ",
```

VS Code version info:
```
Version: 1.74.0 (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

**Comment by srmeyers** [comment]
Thanks @PKief!!! 1.3.1 is now published with your fix.

**Comment by eljenso** [comment]
Thanks @PKief for solving this issue so fast. 👍
