### ISSUE TITLE
Ability for whitespace characters

### ISSUE THREAD

**Issue by jkovalchik** [srmeyers/git-prefix#4]
It would be nice to be able to use newlines (or other whitespace characters for that matter) in the "Replacement" setting so, for instance, a couple newlines could be inserted after the branch ($1) in the commit message.

**Comment by ddcq** [comment]
I've just submit a pull request with which you'll be able to do something like that. I hope.

**Comment by srmeyers** [comment]
Git Prefix 1.2.0 is now available with a new replacementIsFunction option.  Check this option, and set the Replacement to something like `` `(${p1})\n\n` ``
