### ISSUE TITLE
Add suffix

### ISSUE THREAD

**Issue by Kenobi-the-2nd** [srmeyers/git-prefix#6]
It would be useful to also have the ability to append something to the end of the message. This is what I typically do when doing commits. Is there a way to do this currently? If not, it would be a great add-on!

**Comment by kruzyk** [comment]
+1

**Comment by Kenobi-the-2nd** [comment]
A new setting `gitPrefix.isSuffix` was added in version 1.3.0 that allows appending to the end of the commit message. Closing this out.
